### ISSUE TITLE
这个适配32位么，先知上的那篇给的demo不适配32位的

### ISSUE THREAD

**Issue by bcdlbgm** [NoOne-hub/bypass-BeaconEye#2]
如题

**Comment by NoOne-hub** [comment]
> 如题

需要改下代码，代码中均为写死的Rip，如果要改为32位，需要将printf("线程地址:%llx\n", pExcepInfo->ContextRecord->Rip);类似这种改为Eip格式，同时需要查找下偏移修改。思路就是主动造成内存异常，捕获这个内存异常，判断是否在beacon范围内，进行修改内存
